// <auto-generated />
using System;
using LTR.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LTR.Persistence.Migrations
{
    [DbContext(typeof(LtrDbContext))]
    partial class LtrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("LTR.Core.Content.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "ExternalId", "Kind")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("LTR.Core.Content.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArchiveDurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpgChannelId")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasArchive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EpgChannelId");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("LTR.Core.Sources.PlaylistSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastRefreshedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredStreamFormat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sources", (string)null);

                    b.HasDiscriminator<string>("Protocol").HasValue("PlaylistSource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LTR.Core.Sources.M3uSource", b =>
                {
                    b.HasBaseType("LTR.Core.Sources.PlaylistSource");

                    b.Property<string>("EpgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaylistUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("m3u");
                });

            modelBuilder.Entity("LTR.Core.Sources.XtreamSource", b =>
                {
                    b.HasBaseType("LTR.Core.Sources.PlaylistSource");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("xtream");
                });

            modelBuilder.Entity("LTR.Core.Content.Category", b =>
                {
                    b.HasOne("LTR.Core.Sources.PlaylistSource", "Source")
                        .WithMany("Categories")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("LTR.Core.Content.Channel", b =>
                {
                    b.HasOne("LTR.Core.Content.Category", "Category")
                        .WithMany("Channels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LTR.Core.Sources.PlaylistSource", "Source")
                        .WithMany("Channels")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("LTR.Core.Sources.PlaylistSource", b =>
                {
                    b.OwnsOne("LTR.Core.Sources.ProviderCapabilities", "Capabilities", b1 =>
                        {
                            b1.Property<int>("PlaylistSourceId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTimeOffset?>("ProbedAtUtc")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("RequiresLivePathSegment")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("SupportsHls")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("SupportsLive")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("SupportsMpegTs")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("SupportsSeries")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("SupportsShortEpg")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("SupportsVod")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("SupportsXmltvEpg")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlaylistSourceId");

                            b1.ToTable("Sources");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistSourceId");
                        });

                    b.Navigation("Capabilities")
                        .IsRequired();
                });

            modelBuilder.Entity("LTR.Core.Content.Category", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("LTR.Core.Sources.PlaylistSource", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
