using System.Text;
using System.Xml;

namespace LTR.Epg.Xmltv;

/// <summary>
/// Reads an XMLTV guide forwards, without ever holding the document in memory.
/// </summary>
/// <remarks>
/// <para>
/// A full guide for a large subscription runs to 50–200 MB compressed. Loading it into an
/// <c>XmlDocument</c> or even into a string is not an option, so this walks it with
/// <see cref="XmlReader"/> and hands each element to a sink as it passes.
/// </para>
/// <para>
/// Written to tolerate rather than validate. Guides are generated by scripts of varying quality: dates
/// come in half a dozen shapes, <c>stop</c> is often missing, titles arrive in several languages, and
/// downloads are cut short. Each of those is handled or counted; none of them throws.
/// </para>
/// </remarks>
public static class XmltvStreamReader
{
    public static async Task<XmltvReadResult> ReadAsync(
        Stream stream,
        IXmltvSink sink,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(stream);
        ArgumentNullException.ThrowIfNull(sink);

        await using var content = await XmltvStreamOpener.OpenAsync(stream, cancellationToken)
            .ConfigureAwait(false);

        var settings = new XmlReaderSettings
        {
            Async = true,
            IgnoreComments = true,
            IgnoreWhitespace = true,
            IgnoreProcessingInstructions = true,

            // Ignore, not Prohibit: XMLTV documents conventionally declare <!DOCTYPE tv SYSTEM
            // "xmltv.dtd">, and prohibiting it would reject the majority of real guides outright. The
            // null resolver is what keeps that from becoming an external fetch.
            DtdProcessing = DtdProcessing.Ignore,
            XmlResolver = null,
        };

        using var reader = XmlReader.Create(content, settings);
        return await ReadDocumentAsync(reader, sink, cancellationToken).ConfigureAwait(false);
    }

    private static async Task<XmltvReadResult> ReadDocumentAsync(
        XmlReader reader,
        IXmltvSink sink,
        CancellationToken cancellationToken)
    {
        var channels = 0;
        var programmes = 0;
        var skipped = 0;
        var truncated = false;

        try
        {
            while (await reader.ReadAsync().ConfigureAwait(false))
            {
                cancellationToken.ThrowIfCancellationRequested();

                if (reader.NodeType != XmlNodeType.Element)
                {
                    continue;
                }

                switch (reader.LocalName)
                {
                    case "channel":
                        if (await ReadChannelAsync(reader).ConfigureAwait(false) is { } channel)
                        {
                            await sink.ChannelAsync(channel, cancellationToken).ConfigureAwait(false);
                            channels++;
                        }
                        else
                        {
                            skipped++;
                        }

                        break;

                    case "programme":
                        if (await ReadProgrammeAsync(reader).ConfigureAwait(false) is { } programme)
                        {
                            await sink.ProgrammeAsync(programme, cancellationToken).ConfigureAwait(false);
                            programmes++;
                        }
                        else
                        {
                            skipped++;
                        }

                        break;
                }
            }
        }
        catch (XmlException)
        {
            // The document ended inside an element, which is what an interrupted download looks like.
            // Everything already handed to the sink stays; the caller decides whether a partial guide is
            // worth keeping.
            truncated = true;
        }

        return new XmltvReadResult(channels, programmes, skipped, truncated);
    }

    private static async Task<XmltvChannel?> ReadChannelAsync(XmlReader reader)
    {
        var id = reader.GetAttribute("id")?.Trim();
        string? displayName = null;
        string? iconUrl = null;

        await ForEachChildAsync(reader, async child =>
        {
            switch (child.LocalName)
            {
                case "display-name":
                    displayName ??= await ReadElementTextAsync(child).ConfigureAwait(false);
                    break;

                case "icon":
                    iconUrl ??= child.GetAttribute("src")?.Trim();
                    break;
            }
        }).ConfigureAwait(false);

        // Without an id nothing can reference it, which makes the declaration unusable rather than
        // merely incomplete.
        return string.IsNullOrEmpty(id) ? null : new XmltvChannel(id, displayName, NullIfEmpty(iconUrl));
    }

    private static async Task<XmltvProgramme?> ReadProgrammeAsync(XmlReader reader)
    {
        var channelId = reader.GetAttribute("channel")?.Trim();
        var startAttribute = reader.GetAttribute("start");
        var stopAttribute = reader.GetAttribute("stop");

        string? title = null;
        string? description = null;
        string? category = null;
        string? episodeReference = null;
        string? iconUrl = null;

        await ForEachChildAsync(reader, async child =>
        {
            switch (child.LocalName)
            {
                case "title":
                    title ??= await ReadElementTextAsync(child).ConfigureAwait(false);
                    break;

                case "desc":
                    description ??= await ReadElementTextAsync(child).ConfigureAwait(false);
                    break;

                case "category":
                    category ??= await ReadElementTextAsync(child).ConfigureAwait(false);
                    break;

                case "episode-num":
                    episodeReference ??= await ReadElementTextAsync(child).ConfigureAwait(false);
                    break;

                case "icon":
                    iconUrl ??= child.GetAttribute("src")?.Trim();
                    break;
            }
        }).ConfigureAwait(false);

        if (string.IsNullOrEmpty(channelId)
            || !XmltvTimestamp.TryParse(startAttribute, out var startUtc)
            || string.IsNullOrEmpty(title))
        {
            return null;
        }

        // An unreadable stop is treated as an absent one rather than as a reason to drop the programme:
        // the filler can close it from the following entry, and a guide is more useful with an
        // approximate end than with a hole in it.
        DateTimeOffset? stopUtc = XmltvTimestamp.TryParse(stopAttribute, out var parsedStop)
            ? parsedStop
            : null;

        return new XmltvProgramme(
            channelId,
            startUtc,
            stopUtc,
            title,
            description,
            category,
            episodeReference,
            NullIfEmpty(iconUrl));
    }

    /// <summary>
    /// Visits the direct and nested children of the current element, leaving the reader on its end tag.
    /// </summary>
    /// <remarks>
    /// Depth-based rather than <see cref="XmlReader.ReadSubtree"/>, which would need its own async-aware
    /// reader per element and allocate one per programme — hundreds of thousands of them for a real guide.
    /// </remarks>
    private static async Task ForEachChildAsync(XmlReader reader, Func<XmlReader, Task> visit)
    {
        if (reader.IsEmptyElement)
        {
            return;
        }

        var depth = reader.Depth;

        while (await reader.ReadAsync().ConfigureAwait(false))
        {
            if (reader.NodeType == XmlNodeType.EndElement && reader.Depth == depth)
            {
                return;
            }

            if (reader.NodeType == XmlNodeType.Element)
            {
                await visit(reader).ConfigureAwait(false);
            }
        }
    }

    /// <summary>
    /// Reads an element's text, leaving the reader on that element's end tag so the enclosing walk
    /// continues from the right place.
    /// </summary>
    /// <remarks>
    /// Not <c>ReadElementContentAsString</c>, for two reasons: it throws when a description contains
    /// markup, which guides do produce, and it advances past the end tag, which would make the enclosing
    /// loop skip whichever sibling followed.
    /// </remarks>
    private static async Task<string?> ReadElementTextAsync(XmlReader reader)
    {
        if (reader.IsEmptyElement)
        {
            return null;
        }

        var depth = reader.Depth;
        var text = new StringBuilder();

        while (await reader.ReadAsync().ConfigureAwait(false))
        {
            if (reader.NodeType == XmlNodeType.EndElement && reader.Depth == depth)
            {
                break;
            }

            if (reader.NodeType is XmlNodeType.Text or XmlNodeType.CDATA)
            {
                text.Append(reader.Value);
            }
        }

        return NullIfEmpty(text.ToString().Trim());
    }

    private static string? NullIfEmpty(string? value)
    {
        return string.IsNullOrWhiteSpace(value) ? null : value;
    }
}
